- label: Test RayJob Sample YAMLs
  instance_size: large
  image: golang:1.17
  commands:
    # Install Go
    - export PATH=$PATH:/usr/local/go/bin

    # Install kind
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/local/bin/kind

    # Install Docker
    - bash scripts/install-docker.sh

    # Delete dangling clusters
    - kind delete clusters --all

    # Install kubectl.
    - curl -LO https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
    - curl -LO "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl.sha256"
    - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # Create the cluster
    - time kind create cluster --wait 120s --config tests/framework/config/kind-config-buildkite.yml
    - docker ps

    # Now the kind node is running, it exposes port 6443 in the dind-daemon network.
    - kubectl config set clusters.kind-kind.server https://docker:6443

    # Verify that kubectl works
    - kubectl version
    - kubectl cluster-info
    - kubectl get nodes
    - kubectl get pods --all-namespaces

    # Install Helm
    - curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz
    - tar -zxvf helm.tar.gz
    - mv linux-amd64/helm /usr/local/bin/helm
    - helm repo add kuberay https://ray-project.github.io/kuberay-helm/
    - helm repo update

    # Install KubeRay operator
    - pushd ray-operator
    - IMG=kuberay/operator:nightly make docker-image
    - kind load docker-image kuberay/operator:nightly
    - popd

    - pushd helm-chart/kuberay-operator
    # Use helm --wait instead of kubectl wait to prevent flakiness. See #618
    - helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly --wait --timeout=5m0s .
    - popd

    - echo "Kuberay operator successfully installed."

    # Delete kind clusters
    - kind delete clusters --all

    # Install python 3.10 and pip
    - apt-get update
    - apt-get install -y python3.10 python3-pip

    # Install requirements
    - pip install -r tests/framework/config/requirements.txt

    # Run test
    - BUILDKITE_ENV=true python3 tests/test_sample_rayjob_yamls.py
